/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finaloutput;

import java.awt.Color;

/**
 *
 * @author adzyl
 */
public class CashWithdrawal extends javax.swing.JFrame {

    /**
     * Creates new form CashWithdrawal
     */
    public CashWithdrawal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TextHolder = new javax.swing.JTextField();
        One = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Four = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Five = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        Six = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        Cancel = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        Two = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Three = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Seven = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        Eight = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        Nine = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        Decimal = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        Zero = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        Clear = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        DoubleZero = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        Accept = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(73, 61, 85));

        jPanel2.setBackground(new java.awt.Color(32, 27, 38));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("$");

        TextHolder.setBackground(new java.awt.Color(32, 27, 38));
        TextHolder.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        TextHolder.setForeground(new java.awt.Color(0, 204, 51));
        TextHolder.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TextHolder.setBorder(null);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TextHolder, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(TextHolder))
                .addContainerGap())
        );

        One.setBackground(new java.awt.Color(81, 67, 95));
        One.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        One.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OneMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                OneMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                OneMouseReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("1");

        javax.swing.GroupLayout OneLayout = new javax.swing.GroupLayout(One);
        One.setLayout(OneLayout);
        OneLayout.setHorizontalGroup(
            OneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        OneLayout.setVerticalGroup(
            OneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Four.setBackground(new java.awt.Color(81, 67, 95));
        Four.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Four.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FourMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                FourMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                FourMouseReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("4");

        javax.swing.GroupLayout FourLayout = new javax.swing.GroupLayout(Four);
        Four.setLayout(FourLayout);
        FourLayout.setHorizontalGroup(
            FourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FourLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        FourLayout.setVerticalGroup(
            FourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FourLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addContainerGap())
        );

        Five.setBackground(new java.awt.Color(81, 67, 95));
        Five.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Five.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FiveMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                FiveMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                FiveMouseReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("5");

        javax.swing.GroupLayout FiveLayout = new javax.swing.GroupLayout(Five);
        Five.setLayout(FiveLayout);
        FiveLayout.setHorizontalGroup(
            FiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FiveLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        FiveLayout.setVerticalGroup(
            FiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FiveLayout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Six.setBackground(new java.awt.Color(81, 67, 95));
        Six.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Six.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SixMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SixMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                SixMouseReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("6");

        javax.swing.GroupLayout SixLayout = new javax.swing.GroupLayout(Six);
        Six.setLayout(SixLayout);
        SixLayout.setHorizontalGroup(
            SixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SixLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        SixLayout.setVerticalGroup(
            SixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SixLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Cancel.setBackground(new java.awt.Color(255, 51, 51));
        Cancel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CancelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                CancelMouseReleased(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Cancel");

        javax.swing.GroupLayout CancelLayout = new javax.swing.GroupLayout(Cancel);
        Cancel.setLayout(CancelLayout);
        CancelLayout.setHorizontalGroup(
            CancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CancelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                .addContainerGap())
        );
        CancelLayout.setVerticalGroup(
            CancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CancelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Two.setBackground(new java.awt.Color(81, 67, 95));
        Two.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Two.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TwoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TwoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                TwoMouseReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("2");

        javax.swing.GroupLayout TwoLayout = new javax.swing.GroupLayout(Two);
        Two.setLayout(TwoLayout);
        TwoLayout.setHorizontalGroup(
            TwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TwoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                .addContainerGap())
        );
        TwoLayout.setVerticalGroup(
            TwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TwoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addContainerGap())
        );

        Three.setBackground(new java.awt.Color(81, 67, 95));
        Three.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Three.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ThreeMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ThreeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ThreeMouseReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("3");

        javax.swing.GroupLayout ThreeLayout = new javax.swing.GroupLayout(Three);
        Three.setLayout(ThreeLayout);
        ThreeLayout.setHorizontalGroup(
            ThreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThreeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        ThreeLayout.setVerticalGroup(
            ThreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThreeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Seven.setBackground(new java.awt.Color(81, 67, 95));
        Seven.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Seven.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SevenMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SevenMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                SevenMouseReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("7");

        javax.swing.GroupLayout SevenLayout = new javax.swing.GroupLayout(Seven);
        Seven.setLayout(SevenLayout);
        SevenLayout.setHorizontalGroup(
            SevenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SevenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        SevenLayout.setVerticalGroup(
            SevenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SevenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addContainerGap())
        );

        Eight.setBackground(new java.awt.Color(81, 67, 95));
        Eight.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Eight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EightMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EightMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                EightMouseReleased(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("8");

        javax.swing.GroupLayout EightLayout = new javax.swing.GroupLayout(Eight);
        Eight.setLayout(EightLayout);
        EightLayout.setHorizontalGroup(
            EightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EightLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        EightLayout.setVerticalGroup(
            EightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EightLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Nine.setBackground(new java.awt.Color(81, 67, 95));
        Nine.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Nine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NineMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NineMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                NineMouseReleased(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("9");

        javax.swing.GroupLayout NineLayout = new javax.swing.GroupLayout(Nine);
        Nine.setLayout(NineLayout);
        NineLayout.setHorizontalGroup(
            NineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NineLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                .addContainerGap())
        );
        NineLayout.setVerticalGroup(
            NineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NineLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Decimal.setBackground(new java.awt.Color(81, 67, 95));
        Decimal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Decimal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DecimalMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DecimalMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                DecimalMouseReleased(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("●");

        javax.swing.GroupLayout DecimalLayout = new javax.swing.GroupLayout(Decimal);
        Decimal.setLayout(DecimalLayout);
        DecimalLayout.setHorizontalGroup(
            DecimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DecimalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        DecimalLayout.setVerticalGroup(
            DecimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DecimalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addContainerGap())
        );

        Zero.setBackground(new java.awt.Color(81, 67, 95));
        Zero.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Zero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ZeroMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ZeroMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ZeroMouseReleased(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("0");

        javax.swing.GroupLayout ZeroLayout = new javax.swing.GroupLayout(Zero);
        Zero.setLayout(ZeroLayout);
        ZeroLayout.setHorizontalGroup(
            ZeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ZeroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        ZeroLayout.setVerticalGroup(
            ZeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ZeroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Clear.setBackground(new java.awt.Color(255, 153, 0));
        Clear.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClearMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ClearMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ClearMouseReleased(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Clear");

        javax.swing.GroupLayout ClearLayout = new javax.swing.GroupLayout(Clear);
        Clear.setLayout(ClearLayout);
        ClearLayout.setHorizontalGroup(
            ClearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClearLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        ClearLayout.setVerticalGroup(
            ClearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClearLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
                .addContainerGap())
        );

        DoubleZero.setBackground(new java.awt.Color(81, 67, 95));
        DoubleZero.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        DoubleZero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DoubleZeroMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DoubleZeroMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                DoubleZeroMouseReleased(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("00");

        javax.swing.GroupLayout DoubleZeroLayout = new javax.swing.GroupLayout(DoubleZero);
        DoubleZero.setLayout(DoubleZeroLayout);
        DoubleZeroLayout.setHorizontalGroup(
            DoubleZeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DoubleZeroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        DoubleZeroLayout.setVerticalGroup(
            DoubleZeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DoubleZeroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Accept.setBackground(new java.awt.Color(0, 204, 51));
        Accept.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Accept.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AcceptMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AcceptMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                AcceptMouseReleased(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Accept");

        javax.swing.GroupLayout AcceptLayout = new javax.swing.GroupLayout(Accept);
        Accept.setLayout(AcceptLayout);
        AcceptLayout.setHorizontalGroup(
            AcceptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AcceptLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        AcceptLayout.setVerticalGroup(
            AcceptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AcceptLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Seven, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(One, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Four, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Decimal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Cancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Eight, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Five, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Zero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Two, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Accept, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DoubleZero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Three, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Six, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Nine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Two, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Three, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(One, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Four, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Five, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Six, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Seven, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Eight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Nine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Decimal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Zero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DoubleZero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Accept, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Cancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OneMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OneMousePressed
        // TODO add your handling code here:
        One.setBackground(new Color(57,47,66));
    }//GEN-LAST:event_OneMousePressed

    private void TwoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TwoMousePressed
        // TODO add your handling code here:
        Two.setBackground(new Color(57,47,66));
    }//GEN-LAST:event_TwoMousePressed

    private void ThreeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ThreeMousePressed
        // TODO add your handling code here:
        Three.setBackground(new Color(57,47,66));
    }//GEN-LAST:event_ThreeMousePressed

    private void FourMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FourMousePressed
        // TODO add your handling code here:
        Four.setBackground(new Color(57,47,66));
    }//GEN-LAST:event_FourMousePressed

    private void FiveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FiveMousePressed
        // TODO add your handling code here:
        Five.setBackground(new Color(57,47,66));
    }//GEN-LAST:event_FiveMousePressed

    private void SixMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SixMousePressed
        // TODO add your handling code here:
        Six.setBackground(new Color(57,47,66));
    }//GEN-LAST:event_SixMousePressed

    private void SevenMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SevenMousePressed
        // TODO add your handling code here:
        Seven.setBackground(new Color(57,47,66));
    }//GEN-LAST:event_SevenMousePressed

    private void EightMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EightMousePressed
        // TODO add your handling code here:
        Eight.setBackground(new Color(57,47,66));
    }//GEN-LAST:event_EightMousePressed

    private void NineMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NineMousePressed
        // TODO add your handling code here:
        Nine.setBackground(new Color(57,47,66));
    }//GEN-LAST:event_NineMousePressed

    private void DecimalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DecimalMousePressed
        // TODO add your handling code here:
        Decimal.setBackground(new Color(57,47,66));
    }//GEN-LAST:event_DecimalMousePressed

    private void ZeroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ZeroMousePressed
        // TODO add your handling code here:
        Zero.setBackground(new Color(57,47,66));
    }//GEN-LAST:event_ZeroMousePressed

    private void DoubleZeroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DoubleZeroMousePressed
        // TODO add your handling code here:
        DoubleZero.setBackground(new Color(57,47,66));
    }//GEN-LAST:event_DoubleZeroMousePressed

    private void CancelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelMousePressed
        // TODO add your handling code here:
        Cancel.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_CancelMousePressed

    private void ClearMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClearMousePressed
        // TODO add your handling code here:
        Clear.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_ClearMousePressed

    private void AcceptMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AcceptMousePressed
        // TODO add your handling code here:
        Accept.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_AcceptMousePressed

    private void OneMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OneMouseReleased
        // TODO add your handling code here:
        One.setBackground(new Color(81,67,95));
    }//GEN-LAST:event_OneMouseReleased

    private void TwoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TwoMouseReleased
        // TODO add your handling code here:
        Two.setBackground(new Color(81,67,95));
    }//GEN-LAST:event_TwoMouseReleased

    private void ThreeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ThreeMouseReleased
        // TODO add your handling code here:
        Three.setBackground(new Color(81,67,95));
    }//GEN-LAST:event_ThreeMouseReleased

    private void FourMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FourMouseReleased
        // TODO add your handling code here:
        Four.setBackground(new Color(81,67,95));
    }//GEN-LAST:event_FourMouseReleased

    private void FiveMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FiveMouseReleased
        // TODO add your handling code here:
        Five.setBackground(new Color(81,67,95));
    }//GEN-LAST:event_FiveMouseReleased

    private void SixMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SixMouseReleased
        // TODO add your handling code here:
        Six.setBackground(new Color(81,67,95));
    }//GEN-LAST:event_SixMouseReleased

    private void SevenMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SevenMouseReleased
        // TODO add your handling code here:
        Seven.setBackground(new Color(81,67,95));
    }//GEN-LAST:event_SevenMouseReleased

    private void EightMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EightMouseReleased
        // TODO add your handling code here:
        Eight.setBackground(new Color(81,67,95));
    }//GEN-LAST:event_EightMouseReleased

    private void NineMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NineMouseReleased
        // TODO add your handling code here:
        Nine.setBackground(new Color(81,67,95));
    }//GEN-LAST:event_NineMouseReleased

    private void DecimalMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DecimalMouseReleased
        // TODO add your handling code here:
        Decimal.setBackground(new Color(81,67,95));
    }//GEN-LAST:event_DecimalMouseReleased

    private void ZeroMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ZeroMouseReleased
        // TODO add your handling code here:
        Zero.setBackground(new Color(81,67,95));
    }//GEN-LAST:event_ZeroMouseReleased

    private void DoubleZeroMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DoubleZeroMouseReleased
        // TODO add your handling code here:
        DoubleZero.setBackground(new Color(81,67,95));
    }//GEN-LAST:event_DoubleZeroMouseReleased

    private void CancelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelMouseReleased
        // TODO add your handling code here:
        Cancel.setBackground(new Color(255,51,51));
    }//GEN-LAST:event_CancelMouseReleased

    private void ClearMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClearMouseReleased
        // TODO add your handling code here:]
        Clear.setBackground(new Color(255,153,0));
    }//GEN-LAST:event_ClearMouseReleased

    private void AcceptMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AcceptMouseReleased
        // TODO add your handling code here:
        Accept.setBackground(new Color(0,204,51));
    }//GEN-LAST:event_AcceptMouseReleased

    private void OneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OneMouseClicked
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder(TextHolder.getText());
        sb.append("1");
        TextHolder.setText(sb.toString());
    }//GEN-LAST:event_OneMouseClicked

    private void TwoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TwoMouseClicked
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder(TextHolder.getText());
        sb.append("2");
        TextHolder.setText(sb.toString());
    }//GEN-LAST:event_TwoMouseClicked

    private void ThreeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ThreeMouseClicked
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder(TextHolder.getText());
        sb.append("3");
        TextHolder.setText(sb.toString());
    }//GEN-LAST:event_ThreeMouseClicked

    private void FourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FourMouseClicked
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder(TextHolder.getText());
        sb.append("4");
        TextHolder.setText(sb.toString());
    }//GEN-LAST:event_FourMouseClicked

    private void FiveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FiveMouseClicked
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder(TextHolder.getText());
        sb.append("5");
        TextHolder.setText(sb.toString());
    }//GEN-LAST:event_FiveMouseClicked

    private void SixMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SixMouseClicked
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder(TextHolder.getText());
        sb.append("6");
        TextHolder.setText(sb.toString());
    }//GEN-LAST:event_SixMouseClicked

    private void SevenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SevenMouseClicked
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder(TextHolder.getText());
        sb.append("7");
        TextHolder.setText(sb.toString());
    }//GEN-LAST:event_SevenMouseClicked

    private void EightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EightMouseClicked
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder(TextHolder.getText());
        sb.append("8");
        TextHolder.setText(sb.toString());
    }//GEN-LAST:event_EightMouseClicked

    private void NineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NineMouseClicked
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder(TextHolder.getText());
        sb.append("9");
        TextHolder.setText(sb.toString());
    }//GEN-LAST:event_NineMouseClicked

    private void DecimalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DecimalMouseClicked
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder(TextHolder.getText());
        sb.append(".");
        TextHolder.setText(sb.toString());
    }//GEN-LAST:event_DecimalMouseClicked

    private void ZeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ZeroMouseClicked
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder(TextHolder.getText());
        sb.append("0");
        TextHolder.setText(sb.toString());
    }//GEN-LAST:event_ZeroMouseClicked

    private void DoubleZeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DoubleZeroMouseClicked
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder(TextHolder.getText());
        sb.append("00");
        TextHolder.setText(sb.toString());
    }//GEN-LAST:event_DoubleZeroMouseClicked

    private void CancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_CancelMouseClicked

    private void ClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClearMouseClicked
        // TODO add your handling code here:
        TextHolder.setText("");
    }//GEN-LAST:event_ClearMouseClicked

    private void AcceptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AcceptMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_AcceptMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CashWithdrawal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CashWithdrawal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CashWithdrawal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CashWithdrawal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CashWithdrawal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Accept;
    private javax.swing.JPanel Cancel;
    private javax.swing.JPanel Clear;
    private javax.swing.JPanel Decimal;
    private javax.swing.JPanel DoubleZero;
    private javax.swing.JPanel Eight;
    private javax.swing.JPanel Five;
    private javax.swing.JPanel Four;
    private javax.swing.JPanel Nine;
    private javax.swing.JPanel One;
    private javax.swing.JPanel Seven;
    private javax.swing.JPanel Six;
    private javax.swing.JTextField TextHolder;
    private javax.swing.JPanel Three;
    private javax.swing.JPanel Two;
    private javax.swing.JPanel Zero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
