    /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finaloutput;

import LogoFrames.LogoRegistration;
import java.awt.Color;
import java.awt.Container;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.Timer;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;

/**
 *
 * @author adzyl
 */
public class Registration extends javax.swing.JFrame {

    /**
     * Creates new form Registration
     */
    private static final String filepath = "src\\finaloutput\\AppAccount.json";
    private static final JSONParser Parser = new JSONParser();
    static JSONObject record = new JSONObject();
    static JSONArray users = new JSONArray();
    static JSONObject account = new JSONObject();
    
    private static final int ANIMATION_DELAY = 20;
    private static final Color ORIGINAL_COLOR = new Color(204, 204, 255);
    
    public Registration() {
        setUndecorated(true);
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        if (ConfirmPassTF.getText().isEmpty()) {
            ConfirmPassTF.setText("Confirm Password");
            ConfirmPassTF.setEchoChar((char) 0);
            ConfirmPassTF.setForeground(Color.GRAY);
        }
        if (PassTF.getText().isEmpty()) {
            PassTF.setText("Password");
            PassTF.setEchoChar((char) 0);
            PassTF.setForeground(Color.GRAY);
        }
        applyColorPulseAnimation(jPanel3);
        LogoRegistration frame = new LogoRegistration();
        Container contentPane = frame.getContentPane();
        jPanel10.removeAll();
        jPanel10.add(contentPane);
        jPanel10.revalidate();
        jPanel10.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        BackButton = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        UsernameTF = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        FnameTF = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        LnameTF = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        PassTF = new javax.swing.JPasswordField();
        jPanel8 = new javax.swing.JPanel();
        ConfirmPassTF = new javax.swing.JPasswordField();
        ErrorMessageLabel = new javax.swing.JLabel();
        CreateAccButton = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jPanel2.setBackground(new java.awt.Color(53, 45, 60));

        BackButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BackButton.setForeground(new java.awt.Color(255, 255, 255));
        BackButton.setText("GO BACK");
        BackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BackButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackButton, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(24, 21, 27));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 468, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel9.setBackground(new java.awt.Color(57, 49, 64));

        jPanel7.setBackground(new java.awt.Color(24, 21, 27));

        UsernameTF.setForeground(new java.awt.Color(153, 153, 153));
        UsernameTF.setText("Username");
        UsernameTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                UsernameTFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                UsernameTFFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(UsernameTF)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UsernameTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(24, 21, 27));

        FnameTF.setForeground(new java.awt.Color(153, 153, 153));
        FnameTF.setText("First Name");
        FnameTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                FnameTFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                FnameTFFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FnameTF)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FnameTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(24, 21, 27));

        LnameTF.setForeground(new java.awt.Color(153, 153, 153));
        LnameTF.setText("Last Name");
        LnameTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                LnameTFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                LnameTFFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LnameTF)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LnameTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(24, 21, 27));

        PassTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PassTFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PassTFFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PassTF)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PassTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel8.setBackground(new java.awt.Color(24, 21, 27));

        ConfirmPassTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ConfirmPassTFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ConfirmPassTFFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ConfirmPassTF)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ConfirmPassTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        ErrorMessageLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ErrorMessageLabel.setForeground(new java.awt.Color(255, 0, 0));
        ErrorMessageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        CreateAccButton.setBackground(new java.awt.Color(153, 153, 255));
        CreateAccButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(24, 21, 27), 1, true));
        CreateAccButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CreateAccButtonMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Create Account");

        javax.swing.GroupLayout CreateAccButtonLayout = new javax.swing.GroupLayout(CreateAccButton);
        CreateAccButton.setLayout(CreateAccButtonLayout);
        CreateAccButtonLayout.setHorizontalGroup(
            CreateAccButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreateAccButtonLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );
        CreateAccButtonLayout.setVerticalGroup(
            CreateAccButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreateAccButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ErrorMessageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(CreateAccButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 7, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(ErrorMessageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CreateAccButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(204, 204, 255));
        jTextField1.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 30, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsernameTFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UsernameTFFocusGained
        // TODO add your handling code here:
        if (UsernameTF.getText().equals("Username")) {
            UsernameTF.setText("");
            UsernameTF.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_UsernameTFFocusGained

    private void UsernameTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UsernameTFFocusLost
        // TODO add your handling code here:
        if (UsernameTF.getText().isEmpty()) {
            UsernameTF.setText("Username");
            UsernameTF.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_UsernameTFFocusLost

    private void FnameTFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FnameTFFocusGained
        // TODO add your handling code here:
        if (FnameTF.getText().equals("First Name")) {
            FnameTF.setText("");
            FnameTF.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_FnameTFFocusGained

    private void FnameTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FnameTFFocusLost
        // TODO add your handling code here:
        if (FnameTF.getText().isEmpty()) {
            FnameTF.setText("First Name");
            FnameTF.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_FnameTFFocusLost

    private void LnameTFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LnameTFFocusGained
        // TODO add your handling code here:
        if (LnameTF.getText().equals("Last Name")) {
            LnameTF.setText("");
            LnameTF.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_LnameTFFocusGained

    private void LnameTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LnameTFFocusLost
        // TODO add your handling code here:
        if (LnameTF.getText().isEmpty()) {
            LnameTF.setText("Last Name");
            LnameTF.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_LnameTFFocusLost

    private void PassTFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PassTFFocusGained
        // TODO add your handling code here:
        if (PassTF.getText().equals("Password")) {
            PassTF.setText("");
            PassTF.setEchoChar('●');
            PassTF.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_PassTFFocusGained

    private void PassTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PassTFFocusLost
        // TODO add your handling code here:
        if (PassTF.getText().isEmpty()) {
            PassTF.setText("Password");
            PassTF.setEchoChar((char) 0);
            PassTF.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_PassTFFocusLost

    private void ConfirmPassTFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ConfirmPassTFFocusGained
        // TODO add your handling code here:
        if (ConfirmPassTF.getText().equals("Confirm Password")) {
            ConfirmPassTF.setText("");
            ConfirmPassTF.setEchoChar('●');
            ConfirmPassTF.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_ConfirmPassTFFocusGained

    private void ConfirmPassTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ConfirmPassTFFocusLost
        // TODO add your handling code here:
        if (ConfirmPassTF.getText().isEmpty()) {
            ConfirmPassTF.setText("Confirm Password");
            ConfirmPassTF.setEchoChar((char) 0);
            ConfirmPassTF.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_ConfirmPassTFFocusLost

    private void CreateAccButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateAccButtonMouseClicked
        // TODO add your handling code here:
        String Username = UsernameTF.getText();
        String FName = FnameTF.getText();
        String LName = LnameTF.getText();
        String Pass = PassTF.getText();
        String Cpass = ConfirmPassTF.getText();
        int userNumber = 1; // Initialize userNumber as an integer

        if (FName.equals("First Name") || LName.equals("Last Name") || Pass.equals("Password") || Cpass.equals("Confirm Password")){
            ErrorMessageLabel.setText("Please fill in all the fields");
            return;
        }
        if (!Pass.equals(Cpass)){
            ErrorMessageLabel.setText("Password doesn't match");
            return;
        }

        try {
            filecheck();  
            boolean UsernameExists = false;
            boolean FirstNameExists = false;
            boolean LastNameExists = false;

            for (Object userObj : users) {
                JSONObject user = (JSONObject) userObj;
                String existingUsername = (String) user.get("APP: Username");
                String existingFirstName = (String) user.get("APP: First Name");
                String existingLastName = (String) user.get("APP: Last Name");

                if (existingUsername.equals(Username)) {
                    UsernameExists = true;
                    break;
                }

                if (existingFirstName.equals(FName)) {
                    FirstNameExists = true;
                }

                if (existingLastName.equals(LName)) {
                    LastNameExists = true;
                }

                if (FirstNameExists && LastNameExists) {
                    break;
                }
            }

            if (UsernameExists) {
                ErrorMessageLabel.setText("Username is already taken");
                return;
            }

            if (FirstNameExists && LastNameExists) {
                ErrorMessageLabel.setText("You Already have an account");
                return;
            }

            // Check for existing userNumber
            for (Object userObj : users) {
                JSONObject user = (JSONObject) userObj;
                int existingUserNumber = Integer.parseInt((String) user.get("APP: Number"));

                if (existingUserNumber >= userNumber) {
                    userNumber = existingUserNumber + 1;
                }
            }
            account.put("APP: First Name", FName);
            account.put("APP: Last Name", LName);
            account.put("APP: Username", Username);
            account.put("APP: Password", Pass);
            account.put("APP: Number", String.valueOf(userNumber));
            account.put("BANK: First Name", "");
            account.put("BANK: Last Name", "");
            account.put("BANK: Middle Name", "");
            account.put("BANK: Account ID", "");
            account.put("BANK: Contact Number", "");
            account.put("BANK: Email", "");
            account.put("BANK: Balance", "");
            account.put("BANK: Acount Type", "");
            
            users.add(account);
            record.put("Account List", users);
            save();
            ErrorMessageLabel.setText("");
            JOptionPane.showMessageDialog(null, "Account Created Successfully!", "Information", JOptionPane.INFORMATION_MESSAGE);
            Main frame = new Main();
            frame.setVisible(true);
            dispose();
        } catch (IOException | ParseException ex) {
            Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_CreateAccButtonMouseClicked

    private void BackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackButtonMouseClicked
        // TODO add your handling code here:
        Main frame = new Main();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_BackButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }
    public void save() throws IOException{
        try (FileWriter file = new FileWriter(filepath)) {
            file.write(record.toJSONString());
        }
    }
    public void filecheck() throws FileNotFoundException, IOException, ParseException{
        FileReader reader = new FileReader(filepath);
        
        if (reader.ready()){
            Scanner sc = new Scanner(reader);
            String line = "";
            
            while(sc.hasNext()){
                line = line + sc.nextLine();
            }
            if(!line.equals("")){
                reader.close();
                FileReader reader2 = new FileReader (filepath);
                record = (JSONObject) Parser.parse(reader2);
                users = (JSONArray) record.get("Account List");
            }
        }
    }
    private static void applyColorPulseAnimation(JPanel panel) {
        Timer timer = new Timer(ANIMATION_DELAY, new ActionListener() {
            private final float[] hsbValues = Color.RGBtoHSB(ORIGINAL_COLOR.getRed(), ORIGINAL_COLOR.getGreen(), ORIGINAL_COLOR.getBlue(), null);
            private float hue = hsbValues[0]; // Starting hue value
            private boolean increasing = true; // Flag to indicate if hue is increasing or decreasing

            @Override
            public void actionPerformed(ActionEvent e) {
                if (increasing) {
                    hue += 0.01f; // Increment the hue value
                    if (hue >= 1.0f) {
                        hue = 1.0f; // Clamp the hue value to 1.0
                        increasing = false; // Change direction to start decreasing hue
                    }
                } else {
                    hue -= 0.01f; // Decrement the hue value
                    if (hue <= hsbValues[0]) {
                        hue = hsbValues[0]; // Reset hue value to original hue
                        increasing = true; // Change direction to start increasing hue
                    }
                }

                Color color = Color.getHSBColor(hue, hsbValues[1], hsbValues[2]); // Create color with updated hue
                panel.setBackground(color);
                panel.repaint();
            }
        });

        timer.start();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackButton;
    private javax.swing.JPasswordField ConfirmPassTF;
    private javax.swing.JPanel CreateAccButton;
    private javax.swing.JLabel ErrorMessageLabel;
    private javax.swing.JTextField FnameTF;
    private javax.swing.JTextField LnameTF;
    private javax.swing.JPasswordField PassTF;
    private javax.swing.JTextField UsernameTF;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
